Added Load Data Stage

diff --git a/src/data-persist/docker-classifier-data-persist.yaml b/src/data-persist/docker-classifier-data-persist.yaml
--- a/src/data-persist/docker-classifier-data-persist.yaml
+++ b/src/data-persist/docker-classifier-data-persist.yaml
@@ -96,3 +96,35 @@ services:
         '
         echo "Listing contents of /data/dataset_classifier after transform stage:"
         ls -l /data/Dataset_Classifier 
+
+ load-data:
+    container_name: etl_extract_data
+    image: python:3.11
+    volumes:
+      - Project3Data:/data
+      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
+
+    entrypoint: /bin/sh
+    command:
+      - -c
+      - |
+        if [ -z "$RCLONE_CONTAINER" ]; then
+          echo "ERROR: RCLONE_CONTAINER is not set"
+          exit 1
+        fi
+        echo "Cleaning up existing contents of container..."
+        rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true
+
+        echo "Copying data to container..."
+        rclone copy /data/Dataset_Classifier chi_tacc:$RCLONE_CONTAINER \
+        --progress \
+        --transfers=32 \
+        --checkers=16 \
+        --multi-thread-streams=4 \
+        --fast-list
+
+        echo "Listing directories in container after load stage:"
+        rclone lsd chi_tacc:$RCLONE_CONTAINER
+
+
+
